### ISSUE TITLE
Java error

### ISSUE THREAD

**Issue by dianalow** [jahnog/tensorflow-32-bits-linux#1]
Thank you so much for providing this guide. I'm working on an Odroid XU4 and really needed a solution for this.

I reached the bazel build step but encountered the following error:

Would you have any idea what caused this?

```
FAILED: Build did NOT complete successfully (333 packages loaded, 16092 targets configured)
Internal error thrown during build. Printing stack trace: java.lang.IncompatibleClassChangeError: vtable stub
	at com.google.devtools.build.lib.actions.MapBasedActionGraph.registerAction(MapBasedActionGraph.java:43)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$1.run(SkyframeActionExecutor.java:329)
	at com.google.devtools.build.lib.concurrent.ThrowableRecordingRunnableWrapper.lambda$wrap$0(ThrowableRecordingRunnableWrapper.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dianalow** [comment]
solved this issue by reinstalling keras
